apiVersion: apps/v1
kind: Deployment
metadata:
  name: doggo-rating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doggo-rating
  template:
    metadata:
      labels:
        app: doggo-rating
    spec:
      containers:
      - name: doggo-rating
        image: localhost:5000/doggo-rating-service:latest
        envFrom:
        - configMapRef:
            name: doggo-env
        - secretRef:
            name: doggo-secret
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: doggo-rating
spec:
  selector:
    app: doggo-rating
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
